name: Deploy da API Gateway para GKE

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag da imagem a ser implantada (ex: v1.0.0, latest, sha-do-commit)'
        required: true
        default: 'latest'
      environment:
        description: 'Ambiente para deploy (prod, staging, dev)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      gcp_region:
        description: 'Região do GCP (ex: us-central1)'
        required: false
        default: 'us-central1'
      gke_cluster_name:
        description: 'Nome do cluster GKE'
        required: false

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  NAMESPACE: whatsapp-chatbot
  ARTIFACT_REGISTRY_REPO: api-gateway
  IMAGE_NAME: api-gateway

jobs:
  deploy:
    name: Deploy para ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          token_format: 'access_token'
          create_credentials_file: true
          export_environment_variables: true

      - name: Configurar gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Definir variáveis de região e cluster
        id: set_vars
        run: |
          # Definir a região do GCP
          GCP_REGION="${{ github.event.inputs.gcp_region }}"
          if [ -z "$GCP_REGION" ]; then
            GCP_REGION="${{ secrets.GCP_REGION }}"
            if [ -z "$GCP_REGION" ]; then
              GCP_REGION="us-central1"  # Valor padrão
            fi
          fi
          echo "GCP_REGION=$GCP_REGION" >> $GITHUB_ENV
          echo "gcp_region=$GCP_REGION" >> $GITHUB_OUTPUT
          
          # Definir o nome do cluster GKE
          GKE_CLUSTER_NAME="${{ github.event.inputs.gke_cluster_name }}"
          if [ -z "$GKE_CLUSTER_NAME" ]; then
            GKE_CLUSTER_NAME="${{ secrets.GKE_CLUSTER_NAME }}"
            if [ -z "$GKE_CLUSTER_NAME" ]; then
              echo "ERRO: Nome do cluster GKE não fornecido. Forneça via input ou secret GKE_CLUSTER_NAME."
              exit 1
            fi
          fi
          echo "GKE_CLUSTER_NAME=$GKE_CLUSTER_NAME" >> $GITHUB_ENV
          echo "gke_cluster_name=$GKE_CLUSTER_NAME" >> $GITHUB_OUTPUT

      - name: Autenticar no cluster GKE
        run: |
          echo "Conectando ao cluster ${{ env.GKE_CLUSTER_NAME }} na região ${{ env.GCP_REGION }}..."
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} --region ${{ env.GCP_REGION }}
          
      - name: Configurar acesso do GKE ao Artifact Registry
        run: |
          echo "Configurando acesso do GKE ao Artifact Registry..."
          
          # Obter o nome da conta de serviço do GKE
          GKE_SA=$(kubectl get serviceaccount default -n ${{ env.NAMESPACE }} -o jsonpath='{.metadata.name}' 2>/dev/null || echo "default")
          echo "Conta de serviço do Kubernetes: $GKE_SA"
          
          # Verificar se o namespace existe, se não, criá-lo
          if ! kubectl get namespace ${{ env.NAMESPACE }} &> /dev/null; then
            echo "Criando namespace ${{ env.NAMESPACE }}..."
            kubectl apply -f k8s/namespace.yaml
          fi
          
          # Criar um secret do tipo docker-registry para autenticação no Artifact Registry
          echo "Criando secret para autenticação no Artifact Registry..."
          kubectl create secret docker-registry gcr-json-key \
            --namespace=${{ env.NAMESPACE }} \
            --docker-server=${{ env.GCP_REGION }}-docker.pkg.dev \
            --docker-username=_json_key \
            --docker-password="$GOOGLE_CREDENTIALS" \
            --docker-email=not-needed@example.com \
            -o yaml --dry-run=client | kubectl apply -f -
          
          # Adicionar o secret à conta de serviço default
          echo "Adicionando secret à conta de serviço default..."
          kubectl patch serviceaccount default \
            -n ${{ env.NAMESPACE }} \
            -p '{"imagePullSecrets": [{"name": "gcr-json-key"}]}' \
            --type=merge
          
      - name: Verificar se a imagem existe no Artifact Registry
        id: check_image
        run: |
          IMAGE_PATH="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}"
          
          if gcloud artifacts docker images describe $IMAGE_PATH > /dev/null 2>&1; then
            echo "A imagem $IMAGE_PATH existe no Artifact Registry."
            echo "image_exists=true" >> $GITHUB_OUTPUT
          else
            echo "ERRO: A imagem $IMAGE_PATH não existe no Artifact Registry."
            echo "image_exists=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Atualizar a imagem no manifesto de Deployment
        if: steps.check_image.outputs.image_exists == 'true'
        run: |
          IMAGE_PATH="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}"
          sed -i "s|IMAGE_URL|$IMAGE_PATH|g" k8s/api-gateway-deployment.yaml
          
          echo "Manifesto atualizado com a imagem: $IMAGE_PATH"
          cat k8s/api-gateway-deployment.yaml | grep -A 3 "image:"

      - name: Aplicar os manifestos do Kubernetes
        run: |
          echo "Aplicando manifestos Kubernetes no namespace ${{ env.NAMESPACE }}..."
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/api-gateway-deployment.yaml -n ${{ env.NAMESPACE }}
          kubectl apply -f k8s/api-gateway-service.yaml -n ${{ env.NAMESPACE }}
          kubectl apply -f k8s/network-policy.yaml -n ${{ env.NAMESPACE }}
          
      - name: Verificar status do rollout
        id: rollout
        continue-on-error: true
        run: |
          echo "Verificando status do rollout..."
          kubectl rollout status deployment/api-gateway -n ${{ env.NAMESPACE }} --timeout=180s
          
      - name: Diagnosticar problemas do deployment
        if: steps.rollout.outcome == 'failure'
        run: |
          echo "O rollout não foi concluído dentro do tempo limite. Verificando problemas..."
          
          echo "=== Pods do Deployment ==="
          kubectl get pods -l app=api-gateway -n ${{ env.NAMESPACE }} -o wide
          
          echo "=== Descrição dos Pods ==="
          POD_NAME=$(kubectl get pods -l app=api-gateway -n ${{ env.NAMESPACE }} -o jsonpath='{.items[0].metadata.name}')
          if [ -n "$POD_NAME" ]; then
            kubectl describe pod $POD_NAME -n ${{ env.NAMESPACE }}
          else
            echo "Nenhum pod encontrado para o deployment."
          fi
          
          echo "=== Eventos do Namespace ==="
          kubectl get events -n ${{ env.NAMESPACE }} --sort-by='.lastTimestamp'
          
          echo "=== Logs dos Pods (se disponíveis) ==="
          if [ -n "$POD_NAME" ]; then
            kubectl logs $POD_NAME -n ${{ env.NAMESPACE }} --all-containers=true || echo "Não foi possível obter logs"
          fi
          
          echo "=== Status do Deployment ==="
          kubectl get deployment api-gateway -n ${{ env.NAMESPACE }} -o yaml
          
          echo "=== Verificando Secrets ==="
          kubectl get secrets -n ${{ env.NAMESPACE }}
          
          echo "=== Verificando ConfigMaps ==="
          kubectl get configmaps -n ${{ env.NAMESPACE }}
          
          echo "=== Verificando Serviços ==="
          kubectl get services -n ${{ env.NAMESPACE }}
          
          echo "=== Verificando Ingress ==="
          kubectl get ingress -n ${{ env.NAMESPACE }}
          
          echo "=== Verificando Recursos do Cluster ==="
          kubectl top nodes || echo "Comando 'kubectl top nodes' não disponível"
          
          echo "=== Verificando Recursos dos Pods ==="
          kubectl top pods -n ${{ env.NAMESPACE }} || echo "Comando 'kubectl top pods' não disponível"
          
          # Determinar se devemos continuar ou falhar
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "Ambiente de produção detectado. Falhando o workflow devido a problemas no deployment."
            exit 1
          else
            echo "Ambiente não-produção. Continuando o workflow apesar dos problemas no deployment."
          fi
          
      - name: Exibir informações do deployment
        run: |
          echo "Deployment concluído!"
          echo "Pods em execução:"
          kubectl get pods -l app=api-gateway -n ${{ env.NAMESPACE }}
          
          echo "Serviço:"
          kubectl get svc -l app=api-gateway -n ${{ env.NAMESPACE }}
          
          echo "Ingress:"
          kubectl get ingress api-gateway-ingress -n ${{ env.NAMESPACE }} -o wide || echo "Ingress não encontrado"